;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "__exc_push" (func $imp___exc_push))
  (import "env" "__exc_pop" (func $imp___exc_pop))
  (import "env" "__exc_active" (func $imp___exc_active (result i32)))
  (import "env" "__exc_type" (func $imp___exc_type (result i32)))
  (import "env" "__exc_data" (func $imp___exc_data))
  (import "env" "__exc_throw" (func $imp___exc_throw (param i32 i32)))
  (import "env" "__exc_clear" (func $imp___exc_clear))
  (import "env" "__exc_matches" (func $imp___exc_matches (param i32 i32) (result i32)))
  (import "env" "__malloc" (func $imp___malloc (param i32)))
  (import "env" "__free" (func $imp___free (param i32)))
  (import "env" "__console__log" (func $imp___console__log (param i32)))
  (import "env" "__console__error" (func $imp___console__error (param i32)))
  (import "env" "__Math__sqrt" (func $imp___Math__sqrt (param f64) (result f64)))
  (import "env" "__Math__floor" (func $imp___Math__floor (param f64) (result f64)))
  (import "env" "__Math__pow" (func $imp___Math__pow (param f64 f64) (result f64)))
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  (data (i32.const 0) "Hello from MaiaCpp!\00")
  (data (i32.const 20) "This is an error message\00")
  (data (i32.const 48) "sqrt(144) = %.0f\0a\00")
  (data (i32.const 68) "floor(3.7) = %.0f\0a\00")
  (data (i32.const 88) "2^10 = %.0f\0a\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $root f64)
    (local $flr f64)
    (local $pw f64)
    f64.const 144
    call $imp___Math__sqrt
    local.set $root
    f64.const 3.7
    call $imp___Math__floor
    local.set $flr
    f64.const 2
    f64.const 10
    call $imp___Math__pow
    local.set $pw
    i32.const 0
    call $imp___console__log
    i32.const 20
    call $imp___console__error
    i32.const 48
    f64.convert_i32_s
    local.get $root
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 68
    f64.convert_i32_s
    local.get $flr
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 88
    f64.convert_i32_s
    local.get $pw
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    return
    i32.const 0
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
)