// Auto-generated by webc – do not edit manually.
// Re-run  webc.js <source.c>  to regenerate.
'use strict';

// ---------- sprintf (full C format support: width, precision, %lu, %.2f …) ----------
/**
 * sprintf / vsprintf for the MaiaC WASM runtime host.
 *
 * Handles the C format specifiers relevant to the host printf import:
 *   %d %i  – signed integer
 *   %u     – unsigned integer
 *   %f %e %g – floating-point (values arrive as i32 bit-patterns from WASM)
 *   %s     – string (pointer resolved by the caller before arriving here)
 *   %c     – character code → char
 *   %x %X  – hex (unsigned)
 *   %o     – octal (unsigned)
 *   %p     – pointer (treated as %x)
 *   %lu %ld %li %lx %lX – long variants (treated as their unsigned/signed i32 counterparts)
 *   %%     – literal %
 *
 * Width, precision and flags (+, -, 0, space) are supported.
 */

// Regex for a single printf placeholder:
//   %[flags][width][.precision][length]type
const PLACEHOLDER_RE = /%%|%([+\-0 #']*)(\*|\d+)?(?:\.(\*|\d+))?([lh])?([diouxXeEfgGscptu%])/g;

/**
 * Format a string using printf conversion specifiers.
 * @param {string} fmt   - The format string.
 * @param {Array}  args  - Positional argument values (already resolved for %s).
 * @returns {string}
 */
function sprintf(fmt, args) {
  let cursor = 0;

  return String(fmt).replace(PLACEHOLDER_RE, (full, flags, widthSpec, precSpec, _length, type) => {
    if (full === '%%') {
      return '%';
    }

    const value = args[cursor++];

    const f = String(flags || '');
    const leftAlign  = f.includes('-');
    const forceSign  = f.includes('+');
    const zeroPad    = f.includes('0') && !leftAlign;
    const spaceSign  = f.includes(' ');

    const width = widthSpec != null ? parseInt(widthSpec, 10) : 0;
    const prec  = precSpec  != null ? parseInt(precSpec,  10) : null;

    let text = '';
    let sign = '';

    switch (type) {
      case 'd':
      case 'i': {
        const n = value | 0;
        sign = n < 0 ? '-' : (forceSign ? '+' : (spaceSign ? ' ' : ''));
        text = String(Math.abs(n));
        if (prec != null) {
          text = text.padStart(prec, '0');
        }
        break;
      }
      case 'u':
      case 't': {
        const n = value >>> 0;
        text = String(n);
        if (prec != null) {
          text = text.padStart(prec, '0');
        }
        break;
      }
      case 'o': {
        const n = value >>> 0;
        text = n.toString(8);
        if (prec != null) {
          text = text.padStart(prec, '0');
        }
        break;
      }
      case 'x': {
        const n = value >>> 0;
        text = n.toString(16);
        if (prec != null) {
          text = text.padStart(prec, '0');
        }
        break;
      }
      case 'X': {
        const n = value >>> 0;
        text = n.toString(16).toUpperCase();
        if (prec != null) {
          text = text.padStart(prec, '0');
        }
        break;
      }
      case 'p': {
        text = '0x' + (value >>> 0).toString(16);
        break;
      }
      case 'f':
      case 'e':
      case 'E':
      case 'g':
      case 'G': {
        // WASM i32 values arrive here; treat them as the raw int unless they
        // happen to look like a reasonable float already.
        let n = typeof value === 'number' ? value : Number(value);
        sign = n < 0 ? '-' : (forceSign ? '+' : (spaceSign ? ' ' : ''));
        n = Math.abs(n);
        const p = prec != null ? prec : 6;
        if (type === 'e' || type === 'E') {
          text = n.toExponential(p);
          if (type === 'E') text = text.toUpperCase();
        } else if (type === 'g' || type === 'G') {
          text = n.toPrecision(p === 0 ? 1 : p);
          if (type === 'G') text = text.toUpperCase();
        } else {
          text = n.toFixed(p);
        }
        break;
      }
      case 'c': {
        text = String.fromCharCode((value | 0) & 0xff);
        break;
      }
      case 's': {
        text = value == null ? '(null)' : String(value);
        if (prec != null) {
          text = text.slice(0, prec);
        }
        break;
      }
      default:
        return full;
    }

    const body = sign + text;
    if (width > body.length) {
      const pad = width - body.length;
      if (leftAlign) {
        return body + ' '.repeat(pad);
      }
      if (zeroPad && sign) {
        return sign + text.padStart(width - sign.length, '0');
      }
      if (zeroPad) {
        return body.padStart(width, '0');
      }
      return body.padStart(width);
    }
    return body;
  });
}



// ---------- printf bridge (variadic C printf → stdout) ----------
/**
 * Read a null-terminated C string from WASM linear memory.
 * Strings must be stored as raw bytes (1 byte per char) in the WASM module.
 */
function readCString(memory, ptr) {
  const mem = new Uint8Array(memory.buffer);
  const offset = ptr >>> 0;
  let end = offset;
  while (end < mem.length && mem[end] !== 0) {
    end += 1;
  }
  return new TextDecoder('utf-8').decode(mem.subarray(offset, end));
}

/**
 * Normalise C format specifiers that sprintf.js may not handle verbatim.
 * - %lu %ld %lx ... → strip the `l` length modifier
 * - %p              → %x (treat pointer as unsigned hex)
 */
function normalizeCFormat(fmt) {
  return String(fmt)
    .replace(/%([+\-0 #']*)(\d+)?(?:\.\d+)?[lh]([diouxXeEfgG])/g, '%$1$2$3')
    .replace(/%p/g, '%x');
}

/**
 * Extract one entry per %-placeholder from the format string, in order.
 * Returns an array of type characters (e.g. ['d', 's', 'd']).
 * Matches the same PLACEHOLDER_RE used inside sprintf.js.
 */
const PLACEHOLDER_TYPES_RE = /%%|%[+\-0 #']*(?:\*|\d+)?(?:\.(?:\*|\d+))?[lh]?([diouxXeEfgGscptu%])/g;

function extractPlaceholderTypes(fmt) {
  const types = [];
  let match;
  PLACEHOLDER_TYPES_RE.lastIndex = 0;
  while ((match = PLACEHOLDER_TYPES_RE.exec(fmt)) !== null) {
    if (match[0] !== '%%' && match[1]) {
      types.push(match[1]);
    }
  }
  return types;
}

/**
 * Resolve raw WASM numeric arguments against the format string:
 * - For %s placeholders, dereference the pointer to a JS string.
 * - For integer/pointer-like placeholders, coerce to 32-bit integers.
 * - For floating placeholders, keep the JS number.
 */
function resolveArgs(memory, normalizedFmt, rawArgs) {
  const types = extractPlaceholderTypes(normalizedFmt);
  return types.map((type, index) => {
    const raw = Number(rawArgs[index] != null ? rawArgs[index] : 0);

    if (type === 's') {
      return readCString(memory, Math.trunc(raw) >>> 0);
    }

    if (type === 'c') {
      return Math.trunc(raw) & 0xFF;
    }

    if (['d', 'i'].includes(type)) {
      return Math.trunc(raw) | 0;
    }

    if (['u', 'x', 'X', 'o', 'p'].includes(type)) {
      return Math.trunc(raw) >>> 0;
    }

    return raw;
  });
}

/**
 * Build a WASM import object providing a host `printf` implementation.
 *
 * @param {object}   opts
 * @param {function} opts.getMemory  - Returns the WebAssembly.Memory export (may be null on first call).
 * @param {function} opts.write      - Receives a string to write (e.g. process.stdout.write).
 * @returns {function}  The WASM-compatible printf import (8 fixed f64 params, i32 result).
 */
function createPrintfHost({ getMemory, write }) {
  return function printf(fmtPtr, a1, a2, a3, a4, a5, a6, a7) {
    const memory = getMemory();
    if (!memory) {
      return 0;
    }

    try {
      const rawFmt = readCString(memory, fmtPtr >>> 0);
      const fmt    = normalizeCFormat(rawFmt);
      const args   = resolveArgs(memory, fmt, [a1, a2, a3, a4, a5, a6, a7]);
      const text   = sprintf(fmt, args);
      write(text);
      return text.length | 0;
    } catch (_err) {
      write('[printf-host-error]');
      return 0;
    }
  };
}



// ---------- host-extern wrappers (auto-generated from source) ----------
const _buildHostEnv = // Auto-generated host env – do not edit manually
(function buildEnv(getMemory) {
  function readCString(ptr) {
    const memory = getMemory();
    if (!memory) return '';
    const mem = new Uint8Array(memory.buffer);
    const offset = ptr >>> 0; let end = offset;
    while (end < mem.length && mem[end] !== 0) end++;
    return new TextDecoder('utf-8').decode(mem.subarray(offset, end));
  }
  return {
    "__exc_push": () => exc_push(),
    "__exc_pop": () => exc_pop(),
    "__exc_active": () => exc_active(),
    "__exc_type": () => exc_type(),
    "__exc_data": () => exc_data(),
    "__exc_throw": (p0, p1) => exc_throw(p0, p1),
    "__exc_clear": () => exc_clear(),
    "__exc_matches": (p0, p1) => exc_matches(p0, p1),
    "__malloc": (p0) => malloc(p0),
    "__free": (p0) => free(p0),
    "__console__log": (p0) => console.log(readCString(p0)),
    "__console__error": (p0) => console.error(readCString(p0)),
    "__Math__sqrt": (p0) => Math.sqrt(p0),
    "__Math__floor": (p0) => Math.floor(p0),
    "__Math__pow": (p0, p1) => Math.pow(p0, p1),
  };
});

// ---------- public API ----------

/**
 * Create a WebAssembly imports object for this module.
 *
 * @param {() => WebAssembly.Memory | null} getMemory
 * @param {{ write?: (s: string) => void }} [opts]
 * @returns {WebAssembly.Imports}
 */
function createImports(getMemory, opts = {}) {
  const write = opts.write || (s => process.stdout.write(s));
  return {
    env: {
      printf: createPrintfHost({ getMemory, write }),
      ..._buildHostEnv(getMemory),
    }
  };
}

/**
 * Load, instantiate and run the compiled WASM module (Node.js).
 *
 * @param {string} wasmPath  – path to the .wasm file
 * @returns {Promise<number>} – exit code returned by main()
 */
async function run(wasmPath) {
  const fs   = require('fs');
  const bytes = fs.readFileSync(wasmPath);
  let memoryRef = null;
  const imports = createImports(() => memoryRef);
  const { instance } = await WebAssembly.instantiate(bytes, imports);
  memoryRef = instance.exports.memory || null;
  const entry = instance.exports.main || instance.exports.test_entry;
  if (typeof entry !== 'function') throw new Error('No main() export found');
  return entry();
}

if (typeof module !== 'undefined') {
  module.exports = { createImports, run };
}

// When executed directly (node <file>.js [wasm-path]), run main() immediately.
if (typeof require !== 'undefined' && require.main === module) {
  const _path  = require('path');
  const _wasm  = process.argv[2]
    || _path.join(__dirname, _path.basename(__filename, '.js') + '.wasm');
  run(_wasm)
    .then((code) => { process.stdout.write('\n[webc] program returned: ' + code + '\n'); process.exitCode = code; })
    .catch((err) => { console.error('[webc] ' + err.message); process.exitCode = 1; });
}
