;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "__exc_push" (func $imp___exc_push))
  (import "env" "__exc_pop" (func $imp___exc_pop))
  (import "env" "__exc_active" (func $imp___exc_active (result i32)))
  (import "env" "__exc_type" (func $imp___exc_type (result i32)))
  (import "env" "__exc_throw" (func $imp___exc_throw (param i32 i32)))
  (import "env" "__exc_clear" (func $imp___exc_clear))
  (import "env" "__exc_matches" (func $imp___exc_matches (param i32 i32) (result i32)))
  (import "env" "__free" (func $imp___free (param i32)))
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 5 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  (data (i32.const 16) "c = \00")
  (data (i32.const 24) "%d\00")
  (data (i32.const 28) ", \00")
  (data (i32.const 32) ".\0a\00")

  (elem (table $fn_table) (i32.const 0) func $Vector_init $Vector_init__ii $Vector_destroy $Vector_operator_add__N6Vector $main)

  ;; function Vector_init
  (func $Vector_init (param $self i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 8
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $self
    i32.store
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    drop
  )

  ;; function Vector_init__ii
  (func $Vector_init__ii (param $self i32) (param $a i32) (param $b i32)
    (local $__frame i32)
    (local $__tmp_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 16
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $self
    i32.store
    local.get $__frame
    i32.const 8
    i32.add
    local.get $a
    i32.store
    local.get $__frame
    i32.const 12
    i32.add
    local.get $b
    i32.store
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 8
    i32.add
    i32.load
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 4
    i32.add
    local.get $__frame
    i32.const 12
    i32.add
    i32.load
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 8
    i32.add
    i32.load
    drop
    local.get $__frame
    i32.const 12
    i32.add
    i32.load
    drop
  )

  ;; function Vector_destroy
  (func $Vector_destroy (param $self i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 8
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $self
    i32.store
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    drop
  )

  ;; function Vector_operator_add__N6Vector
  (func $Vector_operator_add__N6Vector (param $__maiac_sret i32) (param $self i32) (param $param i32)
    (local $__frame i32)
    (local $temp i32)
    (local $__tmp_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 32
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $__maiac_sret
    i32.store
    local.get $__frame
    i32.const 4
    i32.add
    local.get $self
    i32.store
    local.get $__frame
    i32.const 12
    i32.add
    local.get $param
    i32.const 0
    i32.add
    i32.load
    i32.store
    local.get $__frame
    i32.const 12
    i32.add
    i32.const 4
    i32.add
    local.get $param
    i32.const 4
    i32.add
    i32.load
    i32.store
    local.get $__frame
    i32.const 4
    i32.add
    i32.load
    drop
    local.get $__frame
    i32.const 20
    i32.add
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 4
    i32.add
    i32.load
    i32.const 0
    i32.add
    i32.load
    local.get $__frame
    i32.const 12
    i32.add
    i32.const 0
    i32.add
    i32.load
    i32.add
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 20
    i32.add
    i32.const 4
    i32.add
    local.get $__frame
    i32.const 4
    i32.add
    i32.load
    i32.const 4
    i32.add
    i32.load
    local.get $__frame
    i32.const 12
    i32.add
    i32.const 4
    i32.add
    i32.load
    i32.add
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__maiac_sret
    local.get $__frame
    i32.const 20
    i32.add
    i32.const 0
    i32.add
    i32.load
    i32.store
    local.get $__maiac_sret
    i32.const 4
    i32.add
    local.get $__frame
    i32.const 20
    i32.add
    i32.const 4
    i32.add
    i32.load
    i32.store
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    local.get $__frame
    i32.const 12
    i32.add
    drop
  )

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $a i32)
    (local $b i32)
    (local $c i32)
    (local $__tmp_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 24
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 3
    i32.const 1
    call $Vector_init__ii
    local.get $__frame
    i32.const 8
    i32.add
    i32.const 1
    i32.const 2
    call $Vector_init__ii
    local.get $__frame
    i32.const 16
    i32.add
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 0
    i32.add
    i32.load
    local.get $__frame
    i32.const 8
    i32.add
    i32.const 0
    i32.add
    i32.load
    i32.add
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 16
    i32.add
    i32.const 4
    i32.add
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 4
    i32.add
    i32.load
    local.get $__frame
    i32.const 8
    i32.add
    i32.const 4
    i32.add
    i32.load
    i32.add
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    i32.const 16
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 24
    f64.convert_i32_s
    local.get $__frame
    i32.const 16
    i32.add
    i32.const 0
    i32.add
    i32.load
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 28
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 24
    f64.convert_i32_s
    local.get $__frame
    i32.const 16
    i32.add
    i32.const 4
    i32.add
    i32.load
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 32
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "Vector_init" (func $Vector_init))
  (export "Vector_init__ii" (func $Vector_init__ii))
  (export "Vector_destroy" (func $Vector_destroy))
  (export "Vector_operator_add__N6Vector" (func $Vector_operator_add__N6Vector))
  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
)